### PR TITLE
basic python impl

### PR DESCRIPTION
**Pull request by maganoegi**
Hey! Awesome work on that bash script! I was looking all over the internet for this for Python3, but there is nothing... Here, this is a basic implementation for python of your code - unchanged. It just lacks the input interrupt at 50%, but python people will be happy. It also glitches unfortunately when going too fast :( But so does yours, so I guess there is no way around it

### CODE REVIEW

**Comment by maganoegi** [comment]
BTW, first time that I'm contributing to someone else's code, so forgive me if I'm doing something weird, with this request

**Comment by pollev** [comment]
Hey man!

Couple of things I want to discuss with you.

First of all: That's really awesome! 
I never thought about calling the scripts from python like that, that actually works really nicely. I really appreciate the interest in my script and I think you have a great idea making a python wrapper.

However, I am generally not a fan of making repo's with multiple languages and implementations in them. It tends to be confusing for people who are just looking for a quick solution and don't have the time to actually look at the implementation.

So while I will not merge this request in this repository directly, you have convinced me it would be useful to create a pure python3 implementation (So without the bash scripts).

So I will be doing exactly that, you can find the repository here: 
https://github.com/pollev/python_progress_bar

Give me a day or so to port the bulk of it, and then if you have anything you want to contribute to it, please feel free to make pull requests!

Finally:

> It also glitches unfortunately when going too fast :( But so does yours, so I guess there is no way around it

Could you clarify this please? I was not aware of it and maybe I could fix it

**Comment by maganoegi** [comment]
YES, please make a native python implementation! My wrapper is somewhat clumsy, as I had never before worked with the subprocess module and only done some concurrent programming in JS. It would be a great tool for everybody to have this natively. I dont even know how to go about doing that. 




And about the glitches, I just checked, and it only glitches somewhat when a lot of things are printed very fast or if I remove the generate_some_output_and_sleep().




It works waay better as a standalone script, without the py wrapper. I'd be so excited to see this implemented for python! 




Would you want to collaborate on this one by any chance?




_______________________________


• Sergey Platonov


• IT Engineering student - hepia, Geneva


• Junior IT Project Manager @ JEhepia


• www.svplatonov.com 









On Thu, Feb 13, 2020 at 8:49 AM +0100, "Polle Vanhoof" <notifications@github.com> wrote:












Hey man!


Couple of things I want to discuss with you.


First of all: That's really awesome!

I never thought about calling the scripts from python like that, that actually works really nicely. I really appreciate the interest in my script and I think you have a great idea making a python wrapper.


However, I am generally not a fan of making repo's with multiple languages and implementations in them. It tends to be confusing for people who are just looking for a quick solution and don't have the time to actually look at the implementation.


So while I will not merge this request in this repository directly, you have convinced me it would be useful to create a pure python3 implementation (So without the bash scripts).


So I will be doing exactly that, you can find the repository here:

https://github.com/pollev/python_progress_bar


Give me a day or so to port the bulk of it, and then if you have anything you want to contribute to it, please feel free to make pull requests!


Finally:



It also glitches unfortunately when going too fast :( But so does yours, so I guess there is no way around it



Could you clarify this please? I was not aware of it and maybe I could fix it

**Comment by pollev** [comment]
Hey man,

I just finished the port to native python3.
Please check it out here:
https://github.com/pollev/python_progress_bar

Please test it out, and if you find any bugs, feel free to submit issues or pull requests.

Hope it lives up to your expectations

**Comment by pollev** [comment]
I will close this pull request. Please create issues or pull requests on the other repository.

:)

**Pull request closed without merging**
